spring.application.name=ecom

#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test

spring.datasource.url=jdbc:postgresql://hostname:port/ecom
spring.datasource.username=**username**
spring.datasource.password=**password**

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#Logs the sql queries generated and run by jpa
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#What should happen for each rerun? Recreate db? keep and update schemas...? etc
#spring.jpa.hibernate.ddl-auto=create --scheme created each time
#by default
#spring.jpa.hibernate.ddl-auto=create-drop creates on start and drops on kill
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=none

#Defining custom application properties
images.dir=images/

spring.app.jwtSecret=mySecreteKey1231565416515151654651561651654654165165466545648748456415313543587469874864631561
spring.app.jwtExpirationMs=3000000
spring.ecom.app.jwtCookieName=SpringBootEcom

#logging.level.org.springframework=DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.level.com.example.security.demo=DEBUG

# Needed for aws elastic stalk
#server.port=5000

frontend.url=front-end-url
images.base.url=images-url